FROM quay.io/centos/centos:stream9

MAINTAINER https://github.com/dracutdevs/dracut

ENV container docker
LABEL RUN="docker run -it --name NAME --privileged --ipc=host --net=host --pid=host -e NAME=NAME -e IMAGE=IMAGE IMAGE"

RUN echo 'export DRACUT_NO_XATTR=1 KVERSION=$(cd /lib/modules; ls -1 | tail -1)' > /etc/profile.d/dracut-test.sh

# Install needed packages for the dracut CI container
RUN dnf -y install --enablerepo powertools --setopt=install_weak_deps=False \
    qemu-kvm \
    NetworkManager \
    asciidoc \
    bash-completion \
    bzip2 \
    cryptsetup \
    dash \
    dbus-daemon \
    dhcp-client \
    dhcp-server \
    e2fsprogs \
    gcc \
    git \
    iproute \
    iputils \
    iscsi-initiator-utils \
    kbd \
    kernel \
    kmod-devel \
    lvm2 \
    make \
    mdadm \
    nfs-utils \
    pigz \
    python3-imgcreate \
    rpm-build \
    strace \
    sudo \
    tar \
    tcpdump \
    wget \
    which \
    xz \
    && dnf -y update && dnf clean all

# C9S ships only qemu-kvm, but it disables the KVM accel when it's not
# available
RUN ln -sv /usr/libexec/qemu-kvm /usr/bin/qemu-kvm && \
    ln -sv /usr/libexec/qemu-kvm /usr/bin/qemu-system-$(uname -m)

# Set default command
CMD ["/usr/bin/bash"]
